name: test building image
on:
  pull_request:
    branches:
      - stage

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            NPM_TOKEN=${{ secrets.GH_TOKEN }}
          push: false
          tags: frontend:${{ github.sha }}
